import {ConnectButton} from '@rainbow-me/rainbowkit';
import type {NextPage} from 'next';
import Head from 'next/head';
import {useAutoConnect} from "../hooks/useAutoConnect";
import {useAccount} from "wagmi";
import {Navigation} from "../components/Navigation";
import {TrustedIssuerTable} from "../components/TrustedIssuerTable";
import {Button} from "../components/Buttton";

const Home: NextPage = () => {
  const {address} = useAccount();

  useAutoConnect();

  return (
    <>
      <Head>
        <title>OCI Trusted Issuer List</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon"/>
      </Head>
      <div className="min-h-screen bg-gray-50">
        <Navigation/>
        <div className="mx-auto max-w-6xl px-2 py-10">
          <header>
            <div className="sm:flex sm:items-center">
              <div className="sm:flex-auto">
                <h1 className="text-3xl font-bold leading-tight tracking-tight text-gray-800">Trusted Issuers</h1>
                <p className="mt-2 text-sm text-gray-700">
                  Manage the list of trusted issuers for your OCI ecosystem.
                </p>
              </div>
              <div className="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
                <Button text="Add Trusted Issuer"/>
              </div>
            </div>
          </header>
          <main className="mt-5">
            <TrustedIssuerTable/>
          </main>
        </div>
      </div>
    </>
  );
};

export default Home;
